# Case study definition
# name of the case study. The problem formulation and ouptuts will be printed into the following relative path from main directory : case_studies/config['case_study']
'case_study': 'retour_test'
# number of typical days to consider
'nbr_td': 12
# Dictionnary with the dataframes containing all the data in the form : {'Demand': eud, 'Resources': resources, 'Technologies': technologies, 'End_uses_categories': end_uses_categories, 'Layers_in_out': layers_in_out, 'Storage_characteristics': storage_characteristics, 'Storage_eff_in': storage_eff_in, 'Storage_eff_out': storage_eff_out, 'Time_series': time_series, 'Misc': misc}
'all_data': {}

#Criteria limits
'GWP_limit': 100000 #[ktCO2-eq./year] modify gwp_min if low GWP scenario
'Einv_limit': 100000 #[Gwh/year]
'Cost_limit': 100000 #[beuro/year]

# Relative path from main directory to energyscope subdirectories and files
'data_dir': 'Data/2020'  # Folders containing the csv data files
'es_path': 'energyscope/energy_model'  # Path to the energy model (.mod and .run files)
'cs_path': 'case_studies' # Path to the directory containing the different case studies
'step1_path': 'energyscope/preprocessing/td_selection' # Path to the step1 selection of typical days

# Printing input files for optimisation model
# printing the data in ETSD_data.dat file for the optimisation problem
printing: True
# printing the time related data in ESTD_12TD.dat for the optimisation problem
printing_td: True

# Run options for optimization problem
# path to AMPL licence directory (to adapt by the user), set to None if AMPL is in your PATH variables
# /!\ Don't use "\" but rather "\\" or "/"
'AMPL_path': 
# options for ampl
'ampl_options' : {'show_stats': 3,
                  'log_file': 'output/log.txt',
                  'presolve': 10,
                  'presolve_eps': 1e-7,
                  'presolve_fixeps': 1e-7,
                  'show_boundtol': 0,
                  '_log_input_only': False,
                  'solver': 'gurobi',
                  'gurobi_options' : 'predual=-1 method=2 crossover=0 prepasses=3 barconvtol=1e-6 presolve=-1'
}

# Printing more detailed outputs
'print_hourly_data': True
'print_sankey': True