# Path from main directory to energyscope sub-directories and files
# Case studies directory and name of case study
case_studies_dir: 'case_studies'
case_study_name: 'run_100'
# Folders containing the csv data files
user_data: 'Data/User_data'
developer_data: 'Data/Developer_data'
# Directory to save temporary output files
temp_dir: 'temp'
# Path to the energy model (.mod and .run files)
ES_path: 'STEP_2_EROI_study/ampl_model'
# Output of the step 1 selection of typical days
step1_output: 'STEP_1_TD_selection/TD_of_days.out'

# Printing
# printing the data in ETSD_data.dat file for the optimisation problem
printing: True
# printing the time related data in ESTD_12TD.dat for the optimisation problem
printing_td: True

# Parameters
system_limits:
  GWP_limit: 'Infinity'  # [ktCO2-eq./year]	# Minimum GWP reduction
  COST_limit: 'Infinity'
  EINV_limit: 'Infinity'
# [GW] Electrical interconnections with neighbouring countries
import_capacity: 9.72
# minimum capacities of some technologies
Technologies:
  f_min:
    PV: 3.846
    WIND_ONSHORE: 1.177
    WIND_OFFSHORE: 0.692
    HYDRO_RIVER: 0.11

# Run options
options:
  solver: "/home/jdumas/PycharmProjects/ampl_linux-intel64/cplex"
  show_stats: 1
  log_file: "log.txt"
  cplex_options: ["mipdisplay 5", "mipinterval 1000", "mipgap 0.01", "timelimit 3600"]